### PR TITLE
Mobile UI/redesign of hamburger menu

### PR DESCRIPTION
**Pull request by BartalD**
# Commits

### Details
- Init

### Details
- VFI wants a mobile/tablet UI
- Redesigned Header and side-menu
- Removed .png icons/logos and replaced them with .svg

### Details
- Added .svg icons/logos to our asset-pool

### Details
- Restructured some nesting-issues in html and CSS
- Fitted everything for desktop/tablet/mobile

### Details
- Restructured header to fit the design from sendistovan
- Replaced .png with .svg
- Should now fit for desktop, tablet and mobile

### Details
- Compiled CSS from SCSS

# Testing

## Side-menu
- Access website with desktop/tablet/mobile seperately
### Checklist
- Open and close side-menu
- See if layout seems ok
- See if the language drop-down menu works
- See if everything aligns as it should
## Header
- Access website with desktop/tablet/mobile seperately
### Checklist
- Look at header, see if everything looks ok
- Check for alignment

## Favourites
- Access website with desktop/tablet/mobile seperately
### Checklist
- Open and close favourites
- See if blue heart shows up on desktop and tablet
- Add a/some favourites and see if it behaves as intended

### CODE REVIEW

**Review by MathiasChristiansen — CHANGES_REQUESTED** [review]
image
Close icon is very small on tablet.

**Review by MathiasChristiansen — CHANGES_REQUESTED** [review]
1. Spacing between title and languages is off.  
image
2. Tablets seem to have lost their media query. 
image image
3. Slight offset on arrow and blue heart. 
image
4. And for phone it is off too.
image

**Review by HemmingAskodan — CHANGES_REQUESTED** [review]
image
1. Some width between phone and tablet can actually hide some header menues
2. Diamont icon with the class name indicator is really off. (I see it inherits some class stylings that favourites should have) 
image

image
https://www.spellchecker.net/misspellings/languague
Nothing happens, when clicking on it, but expands if you click right beside it.

image
"Leita eftir tiltøkum" should be vertically in the middle

The above problems were spotted in the stand-alone environment.
Doesn't mean it's not also in the tourism environment.

In tourism environment, the following error appears in the side-menu.
image
Not sure why these errors appear, maybe it's wise to check that out

**Comment by BartalD** [comment]
### Review comments from @MathiasChristiansen 

1. - [ ] Spacing between title and languages is off
    * Not sure how you got the text to look like that @MathiasChristiansen ?
2. - [ ] Tablets seem to have lost their media query
    * Use dimensions from Sendistovan (See e-mail from Oct. 12 - 2023)
3. - [ ] Slight offset on arrow and blue heart
4. - [ ] And for phone it is off too
5. - [ ] X button doesn't work when you've added favourites

**Comment by BartalD** [comment]
### Review Comments from [Hemming Petersen](@HemmingAskodan)

1. - [ ] Some width between phone and tablet can actually hide some header menues
    * This is part of another pull pull request, which will fix the subheader
3. - [ ] Diamond icon with the class name indicator is really off. (I see it inherits some class-stylings that favourites should have)
    * Fixed by locking it with ID
4. - [ ] Typo "languague" - should be "language"
5. - [ ] Label on 'Language'-button not clickable
6. - [ ] "Leita eftir tiltøkum" should be vertically in the middle
    * Not part of the hamburger menu, and therefore out of scope
    * The search box will be moved to the filter side-menu and the Tourism search will be implemented instead
7. - [ ] Error in Tourism Submenu
    * Not part of What'sOn, and therefore out of scope

**Review by Horib — APPROVED** [review]

**Pull request merged**
